### ISSUE TITLE
Add Account Manager

### ISSUE THREAD

**Issue by bbonsack** [TetraTap/SadSky#10]
Add Account Manager Screen. (Redirect to first setup)

**Comment by SharkChips** [comment]
This has been partially implemented in d07bc496f18ffb7cebc26c50bbda5214809aa96f and e9b59537676a94fd9cfe7ed0b5674d1b31cdd90d. Now, all we need is a account editor, and to hook up the add account button

**Comment by SharkChips** [comment]
closed by 1ae6dbf15708ca8cc697c3c120e1e9013c6fda52
