### ISSUE TITLE
Add timeout for requests

### ISSUE THREAD

**Issue by SharkChips** [TetraTap/SadSky#22]
Currently, there's not very good error handling for timed out requests. We need to either handle such errors or add our own timeout counter after each request.

**Comment by bbonsack** [comment]
I think timeout counter would be easiest
On Thu, Apr 14, 2016 at 5:41 PM A. Zhang <notifications@github.com> wrote:

> Currently, there's not very good error handling for timed out requests. We
> need to either handle such errors or add our own timeout counter after each
> request.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TetraTap/SadSky/issues/22>
>
-- 
Sent from my iPhone

This message and any attached documents contain information which may be
confidential, subject to privilege or exempt from disclosure under
applicable law. These materials are intended only for the use of the
intended recipient. If you are not the intended recipient of this
transmission, you are hereby notified that any distribution, disclosure,
printing, copying, storage, modification or the taking of any action in
reliance upon this transmission is strictly prohibited. Delivery of this
message to any person other than the intended recipient shall not
compromise or waive such confidentiality, privilege or exemption from
disclosure as to this communication. If you have received this
communication in error, please immediately notify the sender and delete the
message from your system.
