### ISSUE TITLE
[Regression] Scrollbar appeared after upgrading to onsenui beta.9

### ISSUE THREAD

**Issue by SharkChips** [TetraTap/SadSky#3]
So after upgrading to beta.9 of onsen ui, scrollbars started coming up. Can you get rid of them?

**Comment by bbonsack** [comment]
Yeah I'll take a look in a bit I've got Spanish and math tutors next few
hours later tonight I'll fix it
On Sat, Mar 26, 2016 at 2:31 AM A. Zhang <notifications@github.com> wrote:

> Assigned #3 <https://github.com/Tetraval/SadSky/issues/3> to @bbonsack
> <https://github.com/bbonsack>.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/Tetraval/SadSky/issues/3#event-603897953>
>
-- 
Sent from my iPhone

This message and any attached documents contain information which may be
confidential, subject to privilege or exempt from disclosure under
applicable law. These materials are intended only for the use of the
intended recipient. If you are not the intended recipient of this
transmission, you are hereby notified that any distribution, disclosure,
printing, copying, storage, modification or the taking of any action in
reliance upon this transmission is strictly prohibited. Delivery of this
message to any person other than the intended recipient shall not
compromise or waive such confidentiality, privilege or exemption from
disclosure as to this communication. If you have received this
communication in error, please immediately notify the sender and delete the
message from your system.

**Comment by SharkChips** [comment]
Ok fixed as of 4e88c8ea4e0404ad481bd22c4dacd6f91dafd9e7
