### ISSUE TITLE
Windows Hello Suport

### ISSUE THREAD

**Issue by bbonsack** [TetraTap/SadSky#9]
Same as TouchID support but for windows (Retina scan/fingerprint)

**Comment by SharkChips** [comment]
This is not on the agenda currently. The market share is simply too low.

**Comment by bbonsack** [comment]
That's why it's backloged

On Monday, April 4, 2016, A. Zhang <notifications@github.com> wrote:

> Closed #9 <https://github.com/TetraTap/SadSky/issues/9>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TetraTap/SadSky/issues/9#event-614639099>
>


-- 
Sent from Gmail Mobile
